title: Max's Portfolio
author: Max Noé
description: Max's Portfolio
url: https://mnohe.github.io

linkedin_username: max.noe
github_username: mnohe

# Build settings
plugins:
  - jekyll-seo-tag

collections:
  portfolio:
    output: true
    permalink: /portfolio/:title/
