title: Max's Portfolio
author: Max Noé
description: Projects by Max Noé
url: https://mnohe.github.io
google_analytics: G-DLLG8YSTXP

linkedin_username: max.noe
github_username: mnohe

# Build settings
plugins:
  - jekyll-seo-tag

collections:
  portfolio:
    output: true
    permalink: /portfolio/:title/
